In [ ]:
               # Name :- Rohit Bhardwaj
               # Assignment :- Numpy Basic






In [1]:
import numpy as np

In [2]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)



# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [3]:
array_list

array([1, 2, 3, 4, 5])

In [7]:
array_list.dtype
type(array_list)

numpy.ndarray

In [6]:
type(list_)

list

In [8]:
# Q3. Considering the following changes in the variable, array_list:
    
array_list = np.array(object = list_, dtype = int)

In [9]:
# Consider the below code to answer further questions:


import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [12]:
num_array.shape

(2, 3)

In [13]:
num_array.size

6

In [14]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
data = np.random.randint(0,1,(3,3))

In [20]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
data1 = np.eye(5,5)

In [26]:
data1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
data2 = np.diag([1,1,1,1,1,])

In [28]:
data2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])